# Generated by Django 3.0.6 on 2020-05-27 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성 시간', verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='수정 시간', verbose_name='수정 시간')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='사용자 이메일을 대신해 사용자를 구분합니다.', unique=True, verbose_name='사용자 UID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='사용자 이메일')),
                ('is_staff', models.BooleanField(default=False, verbose_name='사용자의 staff 여부')),
                ('is_active', models.BooleanField(default=True, help_text='사용자가 탈퇴할 경우 False로 변합니다.', verbose_name='사용자의 활동 상태')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
