# Generated by Django 3.0.6 on 2020-07-03 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Main'), (2, 'Story'), (3, 'Event')], verbose_name='배너 종류')),
                ('title', models.CharField(max_length=100, verbose_name='배너 제목')),
                ('description', models.TextField(blank=True, verbose_name='배너 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='배너 배경 이미지')),
                ('start_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='앱 노출 시작 시간')),
                ('end_at', models.DateTimeField(default=datetime.datetime(2099, 12, 31, 23, 59, 59), verbose_name='앱 노출 종료 시간')),
                ('visible', models.BooleanField(default=False, help_text='True로 설정하여 앱에 노출시킬 수 있습니다.', verbose_name='앱 노출 여부')),
            ],
            options={
                'index_together': {('visible', 'start_at', 'end_at')},
            },
        ),
    ]
